version: "2"
run:
  tests: false
  allow-parallel-runners: true
linters:
  default: all
  disable:
    - depguard
    - err113
    - exhaustive
    - exhaustruct
    - forbidigo
    - gochecknoglobals
    - mnd
    - revive
    - varnamelen
  exclusions:
    generated: lax
    paths:
      - (.+)_test\.go
      - test
      - example
formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
  exclusions:
    generated: lax
    paths:
      - (.+)_test\.go
      - test
      - example
